W6D5/Cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

  # get 'cats', to: 'cats#index', as: 'cats'
end

W6D5/Cats/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
    COLORS = ["red", "blue", "yellow", "grey", "white"]
    validates :birth_date, :color, :name, :sex, :description, presence: true
    validates :color, inclusion: {in: COLORS}
    validates :sex, inclusion: {in: %w(M F)}

    include ActionView::Helpers::DateHelper

    def age

        time_ago_in_words(birth_date)

    end
end
# kitty = Cat.new(birth_date: '2015/01/20',color: 'blue', name: 'kitty', sex: 'F',description: 'hi')

W6D5/Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id]) 
        render :show
    end

    def create
        @cat = Cat.new(cat_params)

        if @cat.save
            redirect_to cat_url(@cat)
        else  
            render :new
        end

    end

    private

    def cat_params
        params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end

end

W6D5/Cats/app/helpers/cats_helper.rb
module CatsHelper
end

W6D5/Cats/app/views/cats/_form.html.erb
<% if type == :new %>
    <% action_url = cats_url %>
    <% button_text = "Create Cat" %>
<% elsif type == :edit %>
    <% action_url = cat_url(cat) %>
    <% button_text = "Update Cat" %>
<% end %>

<form action=<%= action_url %> method="POST">
    <% if type == :edit %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>
    
    <label for="name">Name: 
        <input id="name" name="cat[name]" type="text" value=<%= cat.name %>>
    </label>

    <label for="sex">Sex: </label>
    <input id="sex" name="cat[sex]" type="radio" value="M" /> M<br />
    <input id="sex" name="cat[sex]" type="radio" value="F" /> F

    <label for="age">Age: 
        <input id="age" name="cat[age]" type="text" value=<%= cat.age %>>
    </label>
    
    <label for="color">Color: 
        <input id="color" name="cat[color]" type="text" value=<%= cat.color %>>
    </label>

    <label for="description">Description: 
        <textarea id="description" name="cat[description]" type="text" value="<%= cat.description %>">
    </label>

    <input type="submit" value=<%= button_text %>>

    <%= select_tag 'color', options_for_select(COLORS.map{|color| ["#{color}"] }) %>

    

W6D5/Cats/app/views/cats/index.html.erb
<h1>Here are all of our Cats!</h1>



<ul>
    <% @cats.each do |cat| %>
        <li>
            <%= render 'cat', cat: cat, action: :index %>
        </li>
    <% end %>
</ul>

W6D5/Cats/app/views/cats/new.html.erb
<h2>Add a Cat to our website!</h2>

<%= render 'form', cat: @cat, type: :new %>

W6D5/Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>